ARG BUILD_ENV=dev  
ARG ARCH=amd64
ARG GIT_COMMIT_HASH
ARG BUILD_VERSION=0
ARG BASE_REPOSITORY
ARG MSBuild_CONFIG=Debug

FROM --platform=${ARCH} ${BASE_REPOSITORY}/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM --platform=${ARCH} ${BASE_REPOSITORY}/dotnet/sdk:3.1 AS build
ARG MSBuild_CONFIG

WORKDIR /src
COPY ["NuGet.Config", "."]
COPY ["Tranglo1.CustomerIdentity.IdentityServer/Tranglo1.CustomerIdentity.IdentityServer.csproj", "Tranglo1.CustomerIdentity.IdentityServer/"]
COPY ["Tranglo1.CustomerIdentity.Domain/Tranglo1.CustomerIdentity.Domain.csproj", "Tranglo1.CustomerIdentity.Domain/"]
COPY ["Tranglo1.CustomerIdentity.Infrastructure/Tranglo1.CustomerIdentity.Infrastructure.csproj", "Tranglo1.CustomerIdentity.Infrastructure/"]
RUN dotnet restore "Tranglo1.CustomerIdentity.IdentityServer/Tranglo1.CustomerIdentity.IdentityServer.csproj"
COPY . .
WORKDIR "/src/Tranglo1.CustomerIdentity.IdentityServer"
RUN dotnet build "Tranglo1.CustomerIdentity.IdentityServer.csproj" -c ${MSBuild_CONFIG} -o /app/build

FROM build AS publish
ARG MSBuild_CONFIG
RUN dotnet publish "Tranglo1.CustomerIdentity.IdentityServer.csproj" -c ${MSBuild_CONFIG} -o /app/publish

FROM base AS final
ARG BUILD_ENV
ARG GIT_COMMIT_HASH
ARG BUILD_VERSION
ARG MSBuild_CONFIG

LABEL BUILD_CONFIG=${MSBuild_CONFIG}
LABEL GIT_HASH=${GIT_COMMIT_HASH}

ENV DOTNET_ENVIRONMENT=${BUILD_ENV}
ENV ASPNETCORE_ENVIRONMENT=${BUILD_ENV}
ENV BUILD_VERSION=${BUILD_VERSION}
ENV DOTNET_VERSION=ASPNET_3.1

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tranglo1.CustomerIdentity.IdentityServer.dll"]