// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tranglo1.CustomerIdentity.IdentityServer.Infrastructure.Persistance;

namespace Tranglo1.CustomerIdentity.IdentityServer.Infrastructure.Migrations.AuditLog
{
    [DbContext(typeof(AuditLogDbContext))]
    [Migration("20210531082400_AuditLogInitial")]
    partial class AuditLogInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.HasSequence("AuditLogId")
                .IncrementsBy(20)
                .HasMin(1L)
                .HasMax(9223372036854775807L);

            modelBuilder.Entity("Tranglo1.CustomerIdentity.IdentityServer.Security.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "AuditLogId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("varchar(39)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("pk_AuditLogs")
                        .IsClustered();

                    b.ToTable("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
